### ISSUE TITLE
Run development on local

### ISSUE THREAD

**Issue by trikarai** [lordfiSh/sniperelite4maps#16]
how to run repository on local ?

i'm using apache but doesn't work.

what server and configuration must i use ?

**Comment by AtomCrafty** [comment]
I'm running my dev environment using Nginx with the config below, but I believe @lordfiSh uses Apache for the real page.
I should warn you though, this version of the code base will no longer be actively maintained since development has shifted to [this repository](https://github.com/lordfiSh/sniperelite5maps/).

If you want to contribute markers (#15), you don't even need to set up a local copy of the page. You can right-click where you want to place a marker and copy the coordinates (`w=yy.yyy,xx.xxx`) from the url bar.

```
server {
        listen 80;
        listen [::]:80;

        server_name ***************;

        add_header Strict-Transport-Security max-age=15768000;

        root /var/www/***************;

        index home.html;

        location / {
                try_files $uri $uri/ /map.html;
        }
}
```
